### ISSUE TITLE
Error creating volumes on Ubuntu 16.04

### ISSUE THREAD

**Issue by eheydrick** [chef-cookbooks/lvm#105]
We need to install the latest version of `di-ruby-lvm-attrib`
### Cookbook version

3.0.0
### Chef-client version

12.15.19
### Platform Details

Ubuntu 16.04
### Scenario:

Create volumes
### Steps to Reproduce:

Run test-kitchen tests
### Expected Result:

Not bomb out creating volumes
### Actual Result:

```
 Recipe: test::create_thin
         * log[Creating physical volume for test] action write

         * lvm_physical_volume[/dev/loop0] action create
           * chef_gem[di-ruby-lvm-attrib] action install
             - install version 0.0.26 of package di-ruby-lvm-attrib
           * chef_gem[di-ruby-lvm] action install
             - install version 0.2.1 of package di-ruby-lvm

           ================================================================================
           Error executing action `create` on resource 'lvm_physical_volume[/dev/loop0]'
           ================================================================================

           ArgumentError
           -------------
           Unable to load lvm attributes [lvs.yaml] for version [2.02.133(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.26/lib/lvm/attributes/2.02.133(2)/lvs.yaml]

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `new'
           /tmp/kitchen/cache/cookbooks/lvm/libraries/provider_lvm_physical_volume.rb:47:in `action_create'

           Resource Declaration:
           ---------------------


#
           # In /tmp/kitchen/cache/cookbooks/test/recipes/create_thin.rb

            35:   lvm_physical_volume device
            36: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/create_thin.rb:35:in `block in from_file'

           lvm_physical_volume("/dev/loop0") do
             provider Chef::Provider::LvmPhysicalVolume
             action :create
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :lvm_physical_volume
             cookbook_name "test"
             recipe_name "create_thin"
           end

           Platform:
           ---------
           x86_64-linux
```

**Comment by cohencil** [comment]
Getting similar results when creating volume group
cookbook version: 3.1.0
Chef version: 12.15.19
```
  ================================================================================
    Error executing action `create` on resource 'lvm_volume_group[/dev/sdb]'
    ================================================================================

    ArgumentError
    -------------
    Unable to load lvm attributes [lvs.yaml] for version [2.02.166(2)]. The version/object may not be supported or you may need to upgrade the di-ruby-lvm-attrib gem. Error [No such file or directory @ rb_sysopen - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/di-ruby-lvm-attrib-0.0.27/lib/lvm/attributes/2.02.166(2)/lvs.yaml]

    Cookbook Trace:
    ---------------
    /tmp/chef-zero912590331/local-mode-cache/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:58:in `new'
    /tmp/chef-zero912590331/local-mode-cache/cache/cookbooks/lvm/libraries/provider_lvm_volume_group.rb:58:in `action_create'

    ...

    Platform:
    ---------
    x86_64-linux
```

**Comment by cohencil** [comment]
Just noticed an open [pr#51](https://github.com/gregsymons/di-ruby-lvm-attrib/pull/51)

**Comment by tas50** [comment]
I pinged the author about getting that PR merged. Not much I can do until that happens since we depend on the gem.

**Comment by otakumike** [comment]
Hi,

This was having a huge impact on us and it appears only one person (@gregsymons) is able to publish the updated gem for di-ruby-lvm-attrib and that person obviously has a life to live so it might be a little while before he can publish. (version 0.0.28). 

I've temporarily forked his di-ruby-lvm and di-ruby-lvm-attrib repos and published [my own version of the gems](https://rubygems.org/profiles/otakumike) with support for LVM 2.02.166(2). Using this in the LVM cookbook fixes the problem. 

Since it is only temporary, I'm not going to submit a PR to update this cookbook (and I don't think it should get merged anyway), but you can temporarily work around this problem by updating your copy of the lvm cookbook directly. 

In the file `libraries/lvm.rb` update **line 28**:
from > `chef_gem 'di-ruby-lvm-attrib' do`
to > `chef_gem 'otakumike-ruby-lvm-attrib' do`

And in the same file on **line 34**:
from > `chef_gem 'di-ruby-lvm' do`
to > `chef_gem 'otakumike-ruby-lvm' do`

Finally, you need to update `attributes/default.rb` on line 21 to use version `'0.0.28'`. 
from > `default['lvm']['di-ruby-lvm-attrib']['version'] = '0.0.27'`
to > `default['lvm']['di-ruby-lvm-attrib']['version'] = '0.0.28'`

I would recommend only doing this if you really need to, otherwise patience is probably a virtue until the **real** gem can be updated properly. If you have no choice, however, I hope this is helpful to you.

**Comment by jrmuir** [comment]
Also in libraries/lvm.rb lines 21 and 22 need to be modified from di-ruby-lvm* to otakumike-ruby-lvm*.  Otherwise it bombs on not finding di-ruby-lvm* gems.  Not a biggie, just a couple of additional changes for the workaround.  I needed it.

**Comment by otakumike** [comment]
@jrmuir - good catch, sorry for leaving that out!

**Comment by shortdudey123** [comment]
The current version on supermarket converges on Ubuntu 16.04

**Comment by tas50** [comment]
This has been fixed with the new gem
