### ISSUE TITLE
Kitchen Verify does not run bats tests

### ISSUE THREAD

**Issue by roblperry** [chef-cookbooks/lvm#76]
I was going to try to fix an issue with notification, but wanted to first extend that tests to show that it does not work.  But, after doing so, I see that kitchen verify does not run the tests.  I made a change to .kitchen.yml to add a suite that runs the fake::create and run the tests under test/integration/create, some of which need to be associated with resize.  I've not used bats before so I may be lost, but this look pretty broken to me.  I think I could help bring the tests up to date and get them running in kitchen again, but I don't want to dive in as I feel like I might be missing something.  

Can someone educate me as to what I am missing?  Shall I try to chip in on this front?  Perhaps, the tests were removed from .kitchen.yml on purpose for some reason?

**Comment by MarkGibbons** [comment]
@rblperry Hi
I ran a local copy of the kitchen.cloud.yml file using local vagrant instead of digital ocean.  The converge worked fine, verify worked fine and ran all the bats tests.  It doesn't look broken.  Personally I prefer serverspec for new work, but the bats tests did work for me without major changes.

-----> Running bats test suite
 ✓ creates the physical volumes
 ✓ creates the volume group vg-data
 ✓ creates the logical volume logs on vg-data
 ✓ logical volume logs is formatted as ext2 filesystem
 ✓ mounts the logical volume logs to /mnt/logs
 ✓ creates the logical volume home on vg-data
 ✓ logical volume home is formatted as ext2 filesystem
 ✓ mounts the logical volume home to /mnt/home
 ✓ creates the volume group vg-test
 ✓ creates the logical volume 'test' on 'vg-test'
 ✓ logical volume 'test' is formatted as 'ext3' filesystem
 ✓ mounts the logical volume to /mnt/test
 ✓ creates the logical volume 'small' on 'vg-test'
 ✓ logical volume 'test' is formatted as 'ext3' filesystem
 ✓ mounts the logical volume to /mnt/small
 ✓ creates the logical volume using 2% of the available vg extents
 ✓ mode of mounted file systems should match the directory setting
 ✓ Exposed mount point mode should be 755
 ✓ Remount works using fstab information
 ✓ extends the volume group
 ✓ creates the logical volume using 5% of the available vg extents and resizes to 10%
 ✓ creates the logical volume using 5% of the available vg extents and does not resize
 ✓ creates the logical volume at 8MB and resizes to 16MB
 ✓ creates the logical volume at 8MB and does not resize
 ✓ creates and resizes a logical volume that fills the VG
 ✓ verifies the VG has no more extents left
 ✓ resizes the PV to fill the remaining space

**Comment by osgrob** [comment]
@MarkGibbons 

Ah....It seems .kitchen.cloud.yml has been replaced by .kitchen.docker.yml in master, but not updated in the Rakefile.  I'm guessing your looking at 1.4.0 ?  But even then, why exclude this testing from the regular .kitchen.yml ?  If you follow the testing directions in the README.md, you're going to totally miss all of the integration testing. 

Am I still missing something?

Thanks
Rob

**Comment by osgrob** [comment]
@MarkGibbons is right though.  The tests themselves seem fine.  I just missed the need run both fake recipes for the suite of tests.  I've added them tests into .kitchen.yml and am rerunning the tests now.

**Comment by MarkGibbons** [comment]
Sorry, yes, I ran a slightly older version.

I ran with both of these tests in the test suite.
     - recipe[fake::create]
      - recipe[fake::resize]

**Comment by tas50** [comment]
I've fixed the Kitchen config to include the test cookbook.
